server:
  port: 8081

web:
  domain: http://localhost

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
#    url: jdbc:mysql://localhost:3306/blog_community?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/blog_community?serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
# 添加打印日志
logging:
  level:
    root: info
    com.douyuehan.doubao: debug